### PR TITLE
feat: animated page transitions (#392)

### PR DESCRIPTION
**Pull request by tomicvladan**
Added animations for page transitions.

### CODE REVIEW

**Comment by tamas6** [comment]
Anims duration should be down to 1/3 at least for snappy experience, and Let s see what is FairText exactly at “Get Started”

**Comment by tomicvladan** [comment]
Updated to 0.1s. Now I think they look good.

**Review by tamas6 — APPROVED** [review]
LGTM, framer is a great tool, will we rely on it from now on? has great 3D feats: https://www.framer.com/motion/three-introduction/

**Comment by tomicvladan** [comment]
Now when it's installed we can use it wherever it's needed. @tamas6 if you have any suggestion how we can use it to improve UX please let me know.

**Comment by tamas6** [comment]
@IgorShadurin

**Review by IgorShadurin — APPROVED** [review]

**Pull request merged**
