### PR TITLE
feat: changed the order of metamask auth

### PR DESCRIPTION
**Pull request by IgorShadurin**
The users will now first authenticate with Metamask, followed by entering their password to access the decrypted wallet. 

Close: https://github.com/fairDataSociety/fairdrive-theapp/issues/426

### CODE REVIEW

**Comment by tomicvladan** [comment]
It won't be completely clear to users what password they should enter after signing a message. So it would be nice to add some short explanation what the password is used for in the modal.

**Comment by tfius** [comment]
yes, something like:
```
Enter passphrase:
[ xxxxxxxxxxxxxxxxxxx ]                  
Your passphrase is used for decryption/encryption of your data. Do not share. 
```

**Comment by IgorShadurin** [comment]
Screenshot 2023-08-04 at 10 23 02

**Comment by tfius** [comment]
it's still "Enter password", it has to be "Enter passphrase", and then input box, and under input, info. @IgorShadurin

**Comment by IgorShadurin** [comment]
Screenshot 2023-08-04 at 11 52 32
@tfius

**Pull request merged**
