### PR TITLE
Feat/localization

### LINKED ISSUE #418: Please prepare localization file for fairdrive

### PR DESCRIPTION
**Pull request by tomicvladan**
Added support for other languages.

Closes #418

### CODE REVIEW

**Review by tfius — APPROVED** [review]
ai translations - maybe we need to say somewhere that translations were made by AI ?

**Comment by tomicvladan** [comment]
@tfius That's a good idea. Maybe we could add a tooltip to the dropdown?

**Review by IgorShadurin — CHANGES_REQUESTED** [review]
1) On the mobile version, the header breaks due to the new button.

Screenshot 2023-08-09 at 18 58 11

2) "Your passphrase is used for the encryption and decryption of your data. Do not share it."
has not been translated.

3) I tried Russian. There are some phrases that should be changed. Some phrases are not translated.
Since the font does not support Cyrillic, the Russian language looks bad. I propose to leave the Russian language as a separate task, as it requires additional labor.

Screenshot 2023-08-09 at 19 04 58

Screenshot 2023-08-09 at 19 05 33

[ru-RU.json.zip](https://github.com/fairDataSociety/fairdrive-theapp/files/12304638/ru-RU.json.zip)

4) In rs-RS there are phrases containing Cyrillic. It will also not display very well. `"ENTER_PASSPHRASE": "Унесите приступну фразу",`

**Comment by tomicvladan** [comment]
@IgorShadurin 

1. I noticed that but don't know how to fix it. There is no enough space to fit all elements on some tablet screens.
2. Fixed
3. It's strange that it doesn't support Cyrillic. Maybe something else is a problem?
4. Fixed

**Comment by tomicvladan** [comment]
I think now looks good. I had to remove label for "Import account" button on mobile screens.
Screenshot from 2023-08-10 10-32-29

**Pull request merged**
