### PR TITLE
fix: folder label

### PR DESCRIPTION
**Pull request by tomicvladan**
The label "Folder" changed to "New Folder" in the drive menu.

### CODE REVIEW

**Review by tamas6 — COMMENTED** [review]
Unable to create a pod now, blocking a 400 Bad request, not sure related to the changes or  fdp-play isse. Anyway the log say something new (besode 404 and 400):
```
react-dom.development.js:86 Warning: componentWillUpdate has been renamed, and is not recommended for use. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* Rename componentWillUpdate to UNSAFE_componentWillUpdate to suppress this warning in non-strict mode. In React 18.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Identicon
```

**Comment by tomicvladan** [comment]
@tamas6  That error can't be related to this PR, because this PR only changes one label. I tested, and created a pod without any problems. Most likely you tried to create a pod with some special character that is not allowed.

**Comment by tamas6** [comment]
> @tamas6 That error can't be related to this PR, because this PR only changes one label. I tested, and created a pod without any problems. Most likely you tried to create a pod with some special character that is not allowed.

Do you use fdp-play?

**Comment by tomicvladan** [comment]
> > @tamas6 That error can't be related to this PR, because this PR only changes one label. I tested, and created a pod without any problems. Most likely you tried to create a pod with some special character that is not allowed.
> 
> Do you use fdp-play?

No, I'm using bee-1.

**Pull request merged**
