### PR TITLE
Feat/UI improvements

### PR DESCRIPTION
**Pull request by tomicvladan**
Added additional descriptions to the Metamask passphrase modal and the main invites page.

### CODE REVIEW

**Review by IgorShadurin — APPROVED** [review]
pwd_localhost_3000_

I like the idea of explaining to the user what the password is for.
However, it seems to me that this explanation should only be shown if the user wants it. This will help simplify the interface.

An example of how this can be done through tooltip or popovers



Screenshot 2023-09-25 at 15 20 47
Screenshot 2023-09-25 at 15 21 25

wdyt?

**Comment by tomicvladan** [comment]
I agree, using a tooltip would improve UI, but most likely users won't even read the message in such situation. This information is important to be aware of, and keeping it visible it will increase chances that users will actually read it.

**Comment by tfius** [comment]
this is very ugly

**Comment by tomicvladan** [comment]
Maybe this additional text can be moved to a component like this https://headlessui.com/react/disclosure

**Comment by tfius** [comment]
> Maybe this additional text can be moved to a component like this https://headlessui.com/react/disclosure

could be

**Comment by tomicvladan** [comment]
This is the latest change that I made.

When opening this modal for the first time (first time login with Metamask), the message is expanded so the user will be able to see the message:

Screenshot from 2023-09-27 12-59-09

Each next time when the user opens this modal again, the message will be hidden, but it can be opened by clicking the "Read more" section.

Screenshot from 2023-09-27 12-59-14

**Pull request merged**
