### PR TITLE
feat: sidebar for mobile

### PR DESCRIPTION
**Pull request by tomicvladan**
On mobile devices, the left sidebar is transformed to a horizontal menu above the drive area.

### CODE REVIEW

**Comment by IgorShadurin** [comment]
@tomicvladan , can I ask you to attach screenshots of visual changes in the next PR? This makes it easier to pay attention to changes that need to be checked.
I will try to do the same in the next UI PRs.

**Comment by tomicvladan** [comment]
Sure thing, here is how it looks on mobile. For desktop it's the same.

Screenshot from 2023-09-08 10-54-56

**Comment by IgorShadurin** [comment]
The UI has changed on the Desktop version, and potential problems have also appeared.
Now on Desktop the entire menu with actions is displayed, even when we are in root. As root we cannot create a directory or upload a file, although there are buttons. In the development version, these buttons are not displayed as root.

In my personal opinion: the buttons on the left look redundant for Desktop, the old version looks more familiar.

### Current development version
Screenshot 2023-09-08 at 12 40 20

Screenshot 2023-09-08 at 12 40 26

### New version
Screenshot 2023-09-08 at 12 38 57

**Review by IgorShadurin — CHANGES_REQUESTED** [review]
Described in the previous comment

**Comment by tomicvladan** [comment]
They were there by mistake. Now they are hidden on desktop.

**Review by IgorShadurin — APPROVED** [review]

**Pull request merged**
